services:
  - type: web
    name: widiai-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: WIDI_ALLOWED_ORIGINS
        value: https://francolano.github.io/WidiAI/
